// ============================================================================
// CONTEXT : LanguageContext.jsx
// ROLE : Multi-language i18n support for 9 languages (including Arabic RTL layout)
// ============================================================================

import React, { createContext, useContext, useState, useEffect } from "react";

export const translations = {
  en: {
    appName: "MoExpress MARKETPLACE",
    slogan: "Shop More, Live Better!",
    navHome: "Home",
    navCatalog: "Products",
    navHelp: "Help Center",
    navDisputes: "Conflict Center",
    navLegal: "Legal Policies",
    navCart: "Cart",
    navWishlist: "Wishlist",
    navDashboard: "Dashboard",
    navAdmin: "SuperAdmin Panel",
    searchPlaceholder: "Search millions of products on MoExpress...",
    heroTitle: "Big Deals - Up to 70% Off",
    heroBtn: "Shop Now",
    flashDeals: "Flash Deals ⚡",
    topCategories: "Top Categories",
    freeShipping: "Free Shipping",
    securePayment: "100% Secure Payment",
    support247: "24/7 Support",
    addToCart: "Add to Cart",
    buyNow: "Buy Now",
    sellerCenter: "Seller Center",
    proShopBadge: "Verified Pro Shop",
    supplierBadge: "Certified Supplier",
    adsManager: "Meta Ads Manager",
    coinsBalance: "Coins Balance",
    reviews: "Customer Reviews",
    footerCopyright: "© 2026 MoExpress MARKETPLACE. All rights reserved.",
  },
  fr: {
    appName: "MoExpress MARKETPLACE",
    slogan: "Achetez Plus, Vivez Mieux !",
    navHome: "Accueil",
    navCatalog: "Produits",
    navHelp: "Centre d'Aide",
    navDisputes: "Centre de Litiges",
    navLegal: "Mentions Légales",
    navCart: "Panier",
    navWishlist: "Favoris",
    navDashboard: "Tableau de bord",
    navAdmin: "Panneau SuperAdmin",
    searchPlaceholder: "Recherchez des millions de produits sur MoExpress...",
    heroTitle: "Super Offres - Jusqu'à -70%",
    heroBtn: "Découvrir",
    flashDeals: "Ventes Flash ⚡",
    topCategories: "Meilleures Catégories",
    freeShipping: "Livraison Gratuite",
    securePayment: "Paiement 100% Sécurisé",
    support247: "Support 24/7",
    addToCart: "Ajouter au Panier",
    buyNow: "Acheter Maintenant",
    sellerCenter: "Espace Vendeur",
    proShopBadge: "Boutique Pro Certifiée",
    supplierBadge: "Fournisseur Certifié",
    adsManager: "Gestionnaire Pubs Meta",
    coinsBalance: "Solde de Coins",
    reviews: "Avis Clients",
    footerCopyright: "© 2026 MoExpress MARKETPLACE. Tous droits réservés.",
  },
  ar: {
    appName: "مو إكسبريس ماركت بليس",
    slogan: "تسوق أكثر، عش أفضل!",
    navHome: "الرئيسية",
    navCatalog: "المنتجات",
    navHelp: "مركز المساعدة",
    navDisputes: "مركز النزاعات",
    navLegal: "الشروط القانونية",
    navCart: "السلة",
    navWishlist: "المفضلة",
    navDashboard: "لوحة التحكم",
    navAdmin: "لوحة المسؤول الأكبر",
    searchPlaceholder: "ابحث في ملايين المنتجات على مو إكسبريس...",
    heroTitle: "عروض كبرى - خصومات تصل إلى 70%",
    heroBtn: "تسوق الآن",
    flashDeals: "عروض خاطفة ⚡",
    topCategories: "أفضل الفئات",
    freeShipping: "شحن مجاني",
    securePayment: "دفع آمن 100%",
    support247: "دعم 24/7",
    addToCart: "إضافة إلى السلة",
    buyNow: "شراء الآن",
    sellerCenter: "مركز البائعين",
    proShopBadge: "متجر احترافي موثق",
    supplierBadge: "مورد معتمد",
    adsManager: "مدير إعلانات ميتا",
    coinsBalance: "رصيد النقاط",
    reviews: "آراء العملاء",
    footerCopyright: "© 2026 مو إكسبريس ماركت بليس. جميع الحقوق محفوظة.",
  },
  es: {
    appName: "MoExpress MARKETPLACE",
    slogan: "¡Compra Más, Vive Mejor!",
    navHome: "Inicio",
    navCatalog: "Productos",
    navHelp: "Centro de Ayuda",
    navDisputes: "Centro de Disputas",
    navLegal: "Políticas Legales",
    navCart: "Carrito",
    navWishlist: "Deseos",
    navDashboard: "Panel",
    navAdmin: "Panel SuperAdmin",
    searchPlaceholder: "Buscar millones de productos en MoExpress...",
    heroTitle: "Grandes Ofertas - Hasta 70% Dto",
    heroBtn: "Comprar Ahora",
    flashDeals: "Ofertas Flash ⚡",
    topCategories: "Categorías Destacadas",
    freeShipping: "Envío Gratis",
    securePayment: "Pago 100% Seguro",
    support247: "Soporte 24/7",
    addToCart: "Añadir al Carrito",
    buyNow: "Comprar Ya",
    sellerCenter: "Centro de Vendedores",
    proShopBadge: "Tienda Pro Verificada",
    supplierBadge: "Proveedor Certificado",
    adsManager: "Administrador de Anuncios Meta",
    coinsBalance: "Saldo de Monedas",
    reviews: "Reseñas de Clientes",
    footerCopyright: "© 2026 MoExpress MARKETPLACE. Todos los derechos reservados.",
  },
  pt: {
    appName: "MoExpress MARKETPLACE",
    slogan: "Compre Mais, Viva Melhor!",
    navHome: "Início",
    navCatalog: "Produtos",
    navHelp: "Central de Ajuda",
    navDisputes: "Central de Disputas",
    navLegal: "Políticas Legais",
    navCart: "Carrinho",
    navWishlist: "Favoritos",
    navDashboard: "Painel",
    navAdmin: "Painel SuperAdmin",
    searchPlaceholder: "Pesquise milhões de produtos no MoExpress...",
    heroTitle: "Grandes Ofertas - Até 70% OFF",
    heroBtn: "Comprar Agora",
    flashDeals: "Ofertas Relâmpago ⚡",
    topCategories: "Principais Categorias",
    freeShipping: "Frete Grátis",
    securePayment: "Pagamento 100% Seguro",
    support247: "Suporte 24/7",
    addToCart: "Adicionar ao Carrinho",
    buyNow: "Comprar Agora",
    sellerCenter: "Central do Vendedor",
    proShopBadge: "Loja Pro Verificada",
    supplierBadge: "Fornecedor Certificado",
    adsManager: "Gerenciador de Anúncios Meta",
    coinsBalance: "Saldo de Moedas",
    reviews: "Avaliações",
    footerCopyright: "© 2026 MoExpress MARKETPLACE. Todos os direitos reservados.",
  },
  it: {
    appName: "MoExpress MARKETPLACE",
    slogan: "Acquista di Più, Vivi Meglio!",
    navHome: "Home",
    navCatalog: "Prodotti",
    navHelp: "Centro Assistenza",
    navDisputes: "Centro Controversie",
    navLegal: "Note Legali",
    navCart: "Carrello",
    navWishlist: "Preferiti",
    navDashboard: "Dashboard",
    navAdmin: "Pannello SuperAdmin",
    searchPlaceholder: "Cerca milioni di prodotti su MoExpress...",
    heroTitle: "Grandi Offerte - Fino al 70% di Sconto",
    heroBtn: "Acquista Ora",
    flashDeals: "Offerte Lampo ⚡",
    topCategories: "Migliori Categorie",
    freeShipping: "Spedizione Gratuita",
    securePayment: "Pagamento Sicuro 100%",
    support247: "Supporto 24/7",
    addToCart: "Aggiungi al Carrello",
    buyNow: "Acquista Subito",
    sellerCenter: "Centro Venditori",
    proShopBadge: "Negozio Pro Verificato",
    supplierBadge: "Fornitore Certificato",
    adsManager: "Gestione Inserzioni Meta",
    coinsBalance: "Saldo Monete",
    reviews: "Recensioni Clienti",
    footerCopyright: "© 2026 MoExpress MARKETPLACE. Tutti i diritti riservati.",
  },
  de: {
    appName: "MoExpress MARKETPLACE",
    slogan: "Mehr Kaufen, Besser Leben!",
    navHome: "Startseite",
    navCatalog: "Produkte",
    navHelp: "Hilfe-Center",
    navDisputes: "Streitbeilegungszentrum",
    navLegal: "Rechtliches",
    navCart: "Warenkorb",
    navWishlist: "Wunschliste",
    navDashboard: "Dashboard",
    navAdmin: "SuperAdmin-Panel",
    searchPlaceholder: "Suchen Sie Millionen von Produkten auf MoExpress...",
    heroTitle: "Tolle Angebote - Bis zu 70% Rabatt",
    heroBtn: "Jetzt Shoppen",
    flashDeals: "Blitzangebote ⚡",
    topCategories: "Top-Kategorien",
    freeShipping: "Kostenloser Versand",
    securePayment: "100% Sichere Zahlung",
    support247: "24/7 Support",
    addToCart: "In den Warenkorb",
    buyNow: "Jetzt Kaufen",
    sellerCenter: "Verkäufer-Portal",
    proShopBadge: "Verifizierter Pro-Shop",
    supplierBadge: "Zertifizierter Lieferant",
    adsManager: "Meta-Werbeanzeigenmanager",
    coinsBalance: "Münz-Guthaben",
    reviews: "Kundenbewertungen",
    footerCopyright: "© 2026 MoExpress MARKETPLACE. Alle Rechte vorbehalten.",
  },
  ru: {
    appName: "MoExpress MARKETPLACE",
    slogan: "Покупай больше, живи лучше!",
    navHome: "Главная",
    navCatalog: "Товары",
    navHelp: "Центр помощи",
    navDisputes: "Центр споров",
    navLegal: "Правила и условия",
    navCart: "Корзина",
    navWishlist: "Избранное",
    navDashboard: "Личный кабинет",
    navAdmin: "Панель Суперадмина",
    searchPlaceholder: "Поиск миллионов товаров на MoExpress...",
    heroTitle: "Большие скидки - до 70%",
    heroBtn: "Купить сейчас",
    flashDeals: "Молниеносные скидки ⚡",
    topCategories: "Популярные категории",
    freeShipping: "Бесплатная доставка",
    securePayment: "100% Безопасная оплата",
    support247: "Поддержка 24/7",
    addToCart: "В корзину",
    buyNow: "Купить сейчас",
    sellerCenter: "Центр продавцов",
    proShopBadge: "Проверенный Pro Магазин",
    supplierBadge: "Сертифицированный поставщик",
    adsManager: "Менеджер рекламы Meta",
    coinsBalance: "Баланс монет",
    reviews: "Отзывы покупателей",
    footerCopyright: "© 2026 MoExpress MARKETPLACE. Все права защищены.",
  },
  tr: {
    appName: "MoExpress MARKETPLACE",
    slogan: "Daha Çok Alışveriş Yap, Daha İyi Yaşa!",
    navHome: "Anasayfa",
    navCatalog: "Ürünler",
    navHelp: "Yardım Merkezi",
    navDisputes: "Uyuşmazlık Merkezi",
    navLegal: "Yasal Politikalar",
    navCart: "Sepet",
    navWishlist: "Favoriler",
    navDashboard: "Panel",
    navAdmin: "SüperAdmin Paneli",
    searchPlaceholder: "MoExpress'te milyonlarca ürünü arayın...",
    heroTitle: "Büyük Fırsatlar - %70'e Varan İndirim",
    heroBtn: "Şimdi Alışveriş Yap",
    flashDeals: "Flaş Fırsatlar ⚡",
    topCategories: "Popüler Kategoriler",
    freeShipping: "Ücretsiz Kargo",
    securePayment: "%100 Güvenli Ödeme",
    support247: "24/7 Destek",
    addToCart: "Sepete Ekle",
    buyNow: "Hemen Satın Al",
    sellerCenter: "Satıcı Merkezi",
    proShopBadge: "Onaylı Pro Mağaza",
    supplierBadge: "Sertifikalı Tedarikçi",
    adsManager: "Meta Reklam Yöneticisi",
    coinsBalance: "Jeton Bakiyesi",
    reviews: "Müşteri Değerlendirmeleri",
    footerCopyright: "© 2026 MoExpress MARKETPLACE. Tüm hakları saklıdır.",
  },
};

export const SUPPORTED_LANGUAGES = [
  { code: "en", label: "English", flag: "🇺🇸" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
  { code: "ar", label: "العربية", flag: "🇩🇿" },
  { code: "es", label: "Español", flag: "🇪🇸" },
  { code: "pt", label: "Português", flag: "🇵🇹" },
  { code: "it", label: "Italiano", flag: "🇮🇹" },
  { code: "de", label: "Deutsch", flag: "🇩🇪" },
  { code: "ru", label: "Русский", flag: "🇷🇺" },
  { code: "tr", label: "Türkçe", flag: "🇹🇷" },
];

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem("moexpress_lang") || "en");

  const dir = lang === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    localStorage.setItem("moexpress_lang", lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = dir;
  }, [lang, dir]);

  const t = (key) => {
    return translations[lang]?.[key] || translations["en"]?.[key] || key;
  };

  const changeLanguage = (newLang) => {
    setLang(newLang);
  };

  return (
    <LanguageContext.Provider
      value={{
        lang,
        currentLang: lang,
        setLang,
        changeLanguage,
        dir,
        t,
        supportedLanguages: SUPPORTED_LANGUAGES,
        availableLanguages: Object.keys(translations),
      }}
    >
      <div dir={dir}>{children}</div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
